exclude: ['README.md','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2019su-cmpt-379-d1/"
leaderboard: "https://sfu-yacc.appspot.com"
semcode: 1194
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Aug 2, 2019"
midterm: "Jun 25, 2019, 10:30-11:20am, Location: BLU 9660"
finalexam: "Aug 9, 2019, 12-3pm, Location: TBA"
instructor: anoop
tas:
  - name: "Vishal Batvia"
    email: vbatvia
    officehour: "Mondays 5:30pm-6:30pm CSIL Labs ASB 9810"
  - name: "Pooya Moradi"
    email: pmoradi
    officehour: "Mondays 5:30pm-6:30pm CSIL Labs ASB 9808"
hwdates:
  - hw: "0"
    startdate: "May 14, 2019"
    deadline: "May 21, 2019"
  - hw: "1"
    startdate: "May 21, 2019"
    deadline: "Jun 4, 2019"
  - hw: "2"
    startdate: "Jun 4, 2019"
    deadline: "Jun 18, 2019"
  - hw: "3"
    startdate: "Jun 25, 2019"
    deadline: "Jul 9, 2019"
  - hw: "4"
    startdate: "Jul 9, 2019"
    deadline: "Jul 30, 2019"
