exclude: ['README.md','assets/demos','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://courses.cs.sfu.ca/2016su-cmpt-379-d1/"
leaderboard: "https://sfu-yacc.appspot.com"
semcode: 1194
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 3, 2018"
midterm: "Oct 30, 2018"
instructor: anoop
tas:
  - name: "Ashkan Alinejad"
    email: aalineja
  - name: "Nadia Ghobadipasha"
    email: nghobadi
  - name: "Yilong (Jetic) Gu"
    email: jeticg
  - name: "Nishant Kambhatla" 
    email: nkambhat
  - name: "Sayyedhassan Shavarani"
    email: sshavara
hwdates:
  - hw: "0"
    startdate: "Sep 11, 2018"
    deadline: "Sep 18, 2018"
  - hw: "1"
    startdate: "Sep 18, 2018"
    deadline: "Oct 2, 2018"
  - hw: "2"
    startdate: "Oct 2, 2018"
    deadline: "Oct 16, 2018"
  - hw: "3"
    startdate: "Oct 16, 2018"
    deadline: "Nov 6, 2018"
  - hw: "4"
    startdate: "Nov 6, 2018"
    deadline: "Nov 20, 2018"
  - hw: "project"
    startdate: "Nov 6, 2018"
    deadline: "Dec 10, 2018 2pm-5pm"
