exclude: ['README.md','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2020fa-cmpt-379-d1/"
semcode: 1207
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 7, 2020"
midterm: "TBD"
finalexam: "TBD"
instructor: anoop
llvmver: "10.0.1"
tas:
  - name: "Navid Rahimi"
    email: navidr
    officehour: "TBD on Zoom"
hwdates:
  - hw: "0"
    startdate: "Sep 9, 2020"
    deadline: "Sep 21, 2020"
    gracedays: "Sep 23, 2020"
  - hw: "1"
    startdate: "Sep 21, 2020"
    deadline: "Oct 5, 2020"
    gracedays: "Oct 7, 2020"
  - hw: "2"
    startdate: "Oct 5, 2020"
    deadline: "Oct 19, 2020"
    gracedays: "Oct 21, 2020"
  - hw: "3"
    startdate: "Oct 19, 2020"
    deadline: "Nov 2, 2020"
    gracedays: "Nov 9, 2020"
  - hw: "4"
    startdate: "Nov 2, 2020"
    deadline: "Nov 23, 2020"
    gracedays: "Nov 30, 2020"
  - hw: "5"
    startdate: "Nov 23, 2020"
    deadline: "Dec 7, 2020"
    gracedays: "None"
quiz:
  - quiz: "0"
    date: "Sep 16, 2020"
  - quiz: "1"
    date: "Sep 30, 2020"
  - quiz: "2"
    date: "Oct 14, 2020"
  - quiz: "3"
    date: "Oct 28, 2020"
  - quiz: "4"
    date: "Nov 13, 2020"
  - quiz: "5"
    date: "Dec 02, 2020"
