exclude: ['README.md','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2021fa-cmpt-379-d1/"
semcode: 1217
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 7, 2021"
midterm: "TBD"
finalexam: "TBD"
instructor: anoop
llvmver: "10.0.1"
tas:
  - name: "Logan Born"
    email: loborn
    officehour: "TBD on Zoom"
hwdates:
  - hw: "0"
    startdate: "Sep 9, 2021"
    deadline: "Sep 21, 2021"
    gracedays: "Sep 23, 2021"
  - hw: "1"
    startdate: "Sep 21, 2021"
    deadline: "Oct 5, 2021"
    gracedays: "Oct 7, 2021"
  - hw: "2"
    startdate: "Oct 5, 2021"
    deadline: "Oct 19, 2021"
    gracedays: "Oct 21, 2021"
  - hw: "3"
    startdate: "Oct 19, 2021"
    deadline: "Nov 2, 2021"
    gracedays: "Nov 9, 2021"
  - hw: "4"
    startdate: "Nov 2, 2021"
    deadline: "Nov 23, 2021"
    gracedays: "Nov 30, 2021"
  - hw: "5"
    startdate: "Nov 23, 2021"
    deadline: "Dec 7, 2021"
    gracedays: "Dec 9, 2021"
quiz:
  - quiz: "0"
    date: "Sep 16, 2021"
  - quiz: "1"
    date: "Sep 30, 2021"
  - quiz: "2"
    date: "Oct 14, 2021"
  - quiz: "3"
    date: "Oct 28, 2021"
  - quiz: "4"
    date: "Nov 13, 2021"
  - quiz: "5"
    date: "Dec 02, 2021"
