exclude: ['README.md','assets/demos','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://courses.cs.sfu.ca/2016su-cmpt-379-d1/"
leaderboard: "https://sfu-yacc.appspot.com"
