exclude: ['README.md','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2021fa-cmpt-379-d1/"
semcode: 1217
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 7, 2021"
midterm: "TBD"
finalexam: "TBD"
instructor: anoop
llvmver: "12.0.1"
llvmconfig: "llvm-config-12"
tas:
  - name: "Logan Born"
    email: loborn
    officehour: "TBD on Zoom"
hwdates:
  - hw: "0"
    startdate: "Sep 8, 2021"
    deadline: "Sep 20, 2021"
    gracedays: "Sep 22, 2021"
  - hw: "1"
    startdate: "Sep 20, 2021"
    deadline: "Oct 4, 2021"
    gracedays: "Oct 6, 2021"
  - hw: "2"
    startdate: "Oct 4, 2021"
    deadline: "Oct 18, 2021"
    gracedays: "Oct 20, 2021"
  - hw: "3"
    startdate: "Oct 18, 2021"
    deadline: "Nov 1, 2021"
    gracedays: "Nov 4, 2021"
  - hw: "4"
    startdate: "Nov 1, 2021"
    deadline: "Nov 22, 2021"
    gracedays: "Nov 24, 2021"
  - hw: "5"
    startdate: "Nov 22, 2021"
    deadline: "Dec 6, 2021"
    gracedays: "Dec 8, 2021"
quiz:
  - quiz: "0"
    date: "Sep 15, 2021"
  - quiz: "1"
    date: "Sep 29, 2021"
  - quiz: "2"
    date: "Oct 13, 2021"
  - quiz: "3"
    date: "Oct 27, 2021"
  - quiz: "4"
    date: "Nov 17, 2021"
  - quiz: "5"
    date: "Dec 01, 2021"
